//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Dreceiptx.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Dreceiptx.UnitTests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;standardBusinessDocumentHeader&quot; : {
        ///    &quot;sender&quot; : {
        ///      &quot;identifier&quot; : {
        ///        &quot;authority&quot; : &quot;GS1&quot;,
        ///        &quot;value&quot; : &quot;9377778071234&quot;
        ///      },
        ///      &quot;contactInformation&quot; : [ {
        ///        &quot;repId&quot; : &quot;1&quot;,
        ///        &quot;repName&quot; : &quot;Dominic Catherin1&quot;,
        ///        &quot;contact&quot; : &quot;Dom Catherin&quot;,
        ///        &quot;emailAddress&quot; : &quot;test@gmail.com&quot;,
        ///        &quot;faxNumber&quot; : &quot;+61 2 12345678&quot;,
        ///        &quot;telephoneNumber&quot; : &quot;+61 2 987654321&quot;,
        ///        &quot;contactTypeIdentifier&quot; : &quot;Sales&quot;
        ///      } ]
        ///    },
        ///    &quot;receiver&quot; : [ { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JavaJson {
            get {
                return ResourceManager.GetString("JavaJson", resourceCulture);
            }
        }
    }
}
